MyBlogProject/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlogBLL.Services.Abstract;
using MyBlogBLL.Services.Concrete;
using MyBlogDomain.Entities;
using MyBlogProject.Models.PortfolioVMs;

namespace MyBlogProject.Controllers
{
    [Authorize]
    public class PortfolioController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly IPortfolioService portfolioService;

        public PortfolioController(UserManager<AppUser> userManager, IPortfolioService portfolioService)
        {
            this.userManager = userManager;
            this.portfolioService = portfolioService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await portfolioService.GetPortfoliosForUserAsync(await userManager.FindByNameAsync(User.Identity.Name));
            return View(values);
        }

        public IActionResult AddPortfolio()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddPortfolio(AddPortfolioVM portfolioVmToBeAdded)
        {
            if (ModelState.IsValid)
            {

                Portfolio NewPortfolio = new();
                NewPortfolio.AppUser = await userManager.FindByNameAsync(portfolioVmToBeAdded.AppUserId);
                NewPortfolio.Name = portfolioVmToBeAdded.Name;
                NewPortfolio.ProjectUrl = portfolioVmToBeAdded.ProjectUrl;

                var filePath = Path.Combine("wwwroot/UserImages", portfolioVmToBeAdded.ProjectPic.FileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    portfolioVmToBeAdded.ProjectPic.CopyTo(stream);
                }

                NewPortfolio.ImageURL = $"/UserImages/{portfolioVmToBeAdded.ProjectPic.FileName}";

                var filePath2 = Path.Combine("wwwroot/UserImages", portfolioVmToBeAdded.ProjectPic2.FileName);

                using (var stream = new FileStream(filePath2, FileMode.Create))
                {
                    portfolioVmToBeAdded.ProjectPic2.CopyTo(stream);
                }


                if (await portfolioService.AddPortfolioForUserByEntitiesAsync(NewPortfolio, await userManager.FindByIdAsync(portfolioVmToBeAdded.AppUserId)))
                    return RedirectToAction("Index");
                return RedirectToAction("Index");

            }
            else
                ModelState.AddModelError(" ", "Please fill the neccessary parts");


            return View();

        }

        [HttpGet]
        public async Task<IActionResult> DeletePortfolio(int portfolioId)
        {
            if (ModelState.IsValid)
            {
                Portfolio portfolio = await portfolioService.GetPortfolioByIdASync(portfolioId);
                if (await portfolioService.RemovePortfolioFromUserListByEntitiesAsync(portfolio, await userManager.FindByNameAsync(User.Identity.Name)))
                    return RedirectToAction("Index");

            }
            ModelState.AddModelError("", "Something went wrong please try again if it continuos contact the help center.");
            return RedirectToAction("Index");


        }
        [HttpGet]
        public async Task<IActionResult> EditPortfolio(int portfolioId)
        {
            Portfolio portfolio = await portfolioService.GetPortfolioByIdASync(portfolioId);
            return View(portfolio);
        }

        [HttpPost]
        public async Task<IActionResult> EditPortfolio(Portfolio portfolioTobeUpdated)
        {
            if (ModelState.IsValid)
            {
                if (await portfolioService.UpdatePortfolioForUserAsync(portfolioTobeUpdated, await userManager.FindByNameAsync(User.Identity.Name)))
                    return RedirectToAction("Index");

            }
            ModelState.AddModelError("", "Something went wrong!");
            return View();


        }
    }
}

MyBlogProject/Views/Portfolio/AddPortfolio.cshtml
@using MyBlogProject.Models.PortfolioVMs
@model AddPortfolioVM
@{
    ViewData["Title"] = "AddPortfolio";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Add Portfolio</h1>
<form class="form-control" method="post" enctype="multipart/form-data">
    <label asp-for="Name">Name</label>
    <input type="text" asp-for="Name" class="form-control" />

    <label asp-for="ProjectUrl"></label>
    <input asp-for="ProjectUrl" type="url" class="form-control" />

    <label asp-for="ProjectPic">Upload Photo</label>
    <input asp-for="ProjectPic" type="file" class="form-control" />
    <span asp-validation-for="ProjectPic" class="text-danger"></span>

    <label asp-for="ProjectPic2">Upload Photo</label>
    <input asp-for="ProjectPic2" type="file" class="form-control" />
    <span asp-validation-for="ProjectPic2" class="text-danger"></span>

    <input asp-for="AppUserId" value="@User.Identity.Name" hidden />
    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit" class="form-control"> Add </button>
</form>

MyBlogProject/Views/Portfolio/EditPortfolio.cshtml
@using MyBlogDomain.Entities
@model Portfolio
@{
    ViewData["Title"] = "EditAbout";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@if (Model == null)
{
    <div class="text-danger">The requested item was not found.</div>
}
else
{
    <h4>Edit Portfolio</h4>
    <form class="form-control" method="post" enctype="multipart/form-data">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" value="@Model.Name" class="form-control" />

        <label asp-for="ProjectUrl"></label>
        <input asp-for="ProjectUrl" type="url" value="@Model.ProjectUrl" class="form-control" />

        <label asp-for="ImageURL">Your Photo</label>
        @if (!string.IsNullOrEmpty(Model.ImageURL))
        {
            <img src="@Model.ImageURL" alt="Current Photo" class="img-fluid" />
        }
        else
        {
            <p>No Image</p>
        }

        <label asp-for="ImageURL">Upload New Photo</label>
        <input asp-for="ImageURL" type="file" class="form-control" />
        <span asp-validation-for="ImageURL" class="text-danger"></span>

        <div class="text-danger" asp-validation-summary="All"></div>
        <button type="submit" class="form-control"> Edit </button>
    </form>
}

MyBlogProject/Views/Portfolio/Index.cshtml
@using MyBlogDomain.Entities
@model List<Portfolio>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h3>Portfolios</h3>
<div class="card-body px-0 pt-0 pb-2">
    <a href="@Url.Action("AddPortfolio","Portfolio")" class="btn btn-secondary">Add New Project</a>
</div>
<div asp-validation-summary="All">

</div>
<div class="card-body px-0 pt-0 pb-2">
    <div class="table-responsive p-0">
        <table class="table align-items-center justify-content-center mb-0">
            <thead>
                <tr>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Project Name</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Project Link</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Image 1</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Image 2</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Delete</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Edit</th>
                </tr>
            </thead>
            @if (Model != null)
            {
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <p class="text-sm font-weight-bold mb-0">@item.Name</p>
                            </td>
                            <td>
                                <a src="@item.ProjectUrl" class="text-sm font-weight-bold mb-0">@item.ProjectUrl</a>
                            </td>
                            <td>
                                @if (!string.IsNullOrEmpty(item.ImageURL))
                                {
                                    <img src="@item.ImageURL" alt="Profile Picture" class="img-fluid" />
                                }
                                else
                                {
                                    <p>No Image</p>
                                }
                            </td>

                            <td class="align-middle">
                                <a href="@Url.Action("DeletePortfolio","Portfolio",new {portfolioId=item.Id })" class="btn btn-danger">Delete</a>
                            </td>
                            <td class="align-middle">
                                <a href="@Url.Action("EditPortfolio","Portfolio",new {portfolioId=item.Id})" class="btn btn-secondary">Edit</a>
                            </td>
                        </tr>

                    }
                </tbody>
            }
            <p class="text-sm font-weight-bold mb-0">Please add your portfolios</p>
        </table>

    </div>
</div>