MyBlogProject/Controllers/AboutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlogBLL.Services.Abstract;
using MyBlogDomain.Entities;
using MyBlogProject.Models.AboutVMs;

namespace MyBlogProject.Controllers
{
    [Authorize]
    public class AboutController : Controller
    {
        private readonly IAboutService aboutService;
        private readonly UserManager<AppUser> userManager;

        public AboutController(IAboutService aboutService, UserManager<AppUser> userManager)
        {
            this.aboutService = aboutService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var About = await aboutService.GetUserAboutByUser(await userManager.FindByNameAsync(User.Identity.Name));

            return View(About);
        }


        public async Task<IActionResult> AddAbout()
        {
            if (aboutService.checkAbout(await userManager.FindByNameAsync(User.Identity.Name)))
                return RedirectToAction("EditAbout");
                
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddAbout(AddAboutVM aboutVM)
        {
            if (ModelState.IsValid)
            {

                About NewAbout = new();
                NewAbout.AppUser = await userManager.FindByNameAsync(aboutVM.AppUserId);
                NewAbout.Title = aboutVM.Title;
                NewAbout.Description = aboutVM.Description;
                NewAbout.Age = aboutVM.Age;
                NewAbout.Name = aboutVM.Name;
                NewAbout.Phone = aboutVM.Phone;
                NewAbout.Mail = User.Identity.Name;
                if (aboutVM.ProfilePic != null && aboutVM.ProfilePic.Length > 0)
                {

                    var filePath = Path.Combine("wwwroot/UserImages", aboutVM.ProfilePic.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        aboutVM.ProfilePic.CopyTo(stream);
                    }

                    NewAbout.ImageURL = $"/UserImages/{aboutVM.ProfilePic.FileName}";
                }

                if (await aboutService.AddAboutByUser(NewAbout))
                    return RedirectToAction("Index");
                return RedirectToAction("Index");

            }
            else
                ModelState.AddModelError(" ", "Please fill the neccessary parts");


            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditAbout(int aboutId)
        {
            About aboutToBeEditted = await aboutService.GetAboutById(aboutId);

            return View(aboutToBeEditted);
        }

        [HttpPost]
        public async Task<IActionResult> EditAbout(About EdittingAbout)
        {
            if (await aboutService.UpdateAboutForUser(EdittingAbout, await userManager.FindByNameAsync(User.Identity.Name)))
                return RedirectToAction("Index");

            return RedirectToAction("Index");
        }
       
        public async Task<IActionResult> RemoveAbout(int aboutId)
        {
            About about = await aboutService.GetAboutById(aboutId);

            if (await aboutService.RemoveAboutForUser(about, await userManager.FindByNameAsync(User.Identity.Name)))
                return RedirectToAction("Index");
            return RedirectToAction("Index");
        }
    }
}

MyBlogProject/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlogBLL.Services.Concrete;

namespace MyBlogProject.Controllers
{
    
    public class DefaultController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
        
        public PartialViewResult HeaderPartial()
        {
            return PartialView();
        }
        
        public PartialViewResult NavBarPartial()
        {
            return PartialView();
        }

        [HttpGet]
        public PartialViewResult PopUpPartial()
        {
            return PartialView();
        }

        public PartialViewResult FeaturePartial()
        {
            return PartialView("~/Views/Feature/FeaturePartial.cshtml");
        }

        //public async Task<PartialViewResult> FeaturePartial()
        //{
        //    var AboutList = aboutService.GetAbouts();
        //    return PartialView(AboutList);

        //}
    }
}
//123456aA

MyBlogProject/Controllers/ExperienceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlogBLL.Services.Abstract;
using MyBlogBLL.Services.Concrete;
using MyBlogDomain.Entities;
using MyBlogProject.Helpers;

namespace MyBlogProject.Controllers
{
    [Authorize(Roles ="StandartUser")]
    public class ExperienceController : Controller
    {
        private readonly IExperienceService eService;
        //private readonly UserHelper _userHelper;
        private readonly UserManager<AppUser> userManager;

        public ExperienceController(IExperienceService eService, UserManager<AppUser> userManager)
        {
            this.eService=eService;
            this.userManager = userManager;
            //this._userHelper = _userHelper;
        }

        public async Task<IActionResult> Index()
        {
            
            return View(await eService.GetUserExperiencesForUser( await userManager.FindByNameAsync(User.Identity.Name)));
        }

        [HttpGet]
        public  IActionResult AddExperience()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddExperience(Experience experience)
        {
            if (await eService.AddingExperienceForUser(await userManager.FindByNameAsync(User.Identity.Name), experience))
                return RedirectToAction("Index");

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditExperience(int experienceId)
        {
            Experience experience = await eService.GetExperienceByIdASync(experienceId);

            return View(experience);
        }

        [HttpPost]
        public async Task<IActionResult> EditExperience(Experience UpdatedExperience)
        {
            if (await eService.UpdateExperienceForUser(UpdatedExperience, await userManager.FindByNameAsync(User.Identity.Name)))
                return RedirectToAction("Index");

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> RemoveExperience(int experienceId)
        {
            Experience experience = await eService.GetExperienceByIdASync(experienceId);

            if (await eService.RemoveExperienceForUser(experience, await userManager.FindByNameAsync(User.Identity.Name)))
                return RedirectToAction("Index");
            return RedirectToAction("Index");


        }


    }
}

MyBlogProject/Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlogBLL.Services.Abstract;
using MyBlogDomain.Entities;
using MyBlogProject.Models.SkillVMs;
using System.Data;

namespace MyBlogProject.Controllers
{
    [Authorize]
    public class SkillController : Controller
    {
        private readonly ISkillService skillService;
        private readonly UserManager<AppUser> userManager;

        public SkillController(ISkillService skillService, UserManager<AppUser> userManager)
        {
            this.skillService = skillService;
            this.userManager = userManager;


        }

        public async Task<IActionResult> Index()
        {
            AppUser person = await userManager.FindByNameAsync(User.Identity.Name);

            var values = await skillService.GetUserSkillsByUser(person);
            return View(values);
        }

        public async Task<IActionResult> AddSkill()
        {
            Skill nw = new Skill();
            return View(nw);
        }

        [HttpPost]
        public async Task<IActionResult> AddSkill(Skill skill)
        {

            AppUser appUser = await userManager.FindByNameAsync(User.Identity.Name);
            //Skill newSkill = new Skill();
            //newSkill.SkillName = skill.SkillName;
            //newSkill.Level = skill.Level;
            if (await skillService.AddingSkillForUser(appUser, skill) == true)
            {
                return RedirectToAction("Index");
            }


            return View();
        }


        [HttpGet]
        public async Task<IActionResult> DeleteSkill(Skill Skill)
        {
            Skill SkillToBeDeleted = await skillService.GetSkillByName(Skill.SkillName);
            AppUser person = await userManager.FindByNameAsync(User.Identity.Name);
            if (SkillToBeDeleted != null)
            {
                if (await skillService.RemoveSkillForUser(SkillToBeDeleted, person))
                    return RedirectToAction("Index");
                //else
                //{
                //    ModelState.AddModelError(" ", "Silme işlemi sırasında bir sıkıntı oluştu.");

                //}

            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditSkill(int id)
        {
            Skill skilltoBeUpdated = await skillService.GetSkillById(id);

            return View(skilltoBeUpdated);
        }

        [HttpPost]
        public async Task<IActionResult> EditSkill(Skill RevisedSkill)
        {

            AppUser person = await userManager.FindByNameAsync(User.Identity.Name);
            if (await skillService.UpdateSkillForUser(RevisedSkill, person))
            { return RedirectToAction("Index"); }

            return RedirectToAction("Index");
        }


    }
}

MyBlogProject/Views/Admin/SideBarPartialView.cshtml
<div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Index","About")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Profile</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Index","Skill")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Skills</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Index","Experience")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-app text-info text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Exprerience</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Index","Edudcation")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Education</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Index","Skill")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Contact Informations</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Index","Default")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Blog</span>
            </a>
        </li>
        <li class="nav-item mt-3">
            <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Account pages</h6>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Logout","Account")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-single-copy-04 text-warning text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Sign Out</span>
            </a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Login","Account")">
                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="ni ni-collection text-info text-sm opacity-10"></i>
                </div>
                <span class="nav-link-text ms-1">Sign In</span>
            </a>
        </li>
            
        }


    </ul>
</div>